# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nnextractor.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'nnextractor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11nnextractor.proto\x12\x0bnnextractor\"\x8f\x01\n\x07NDArray\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05\x62ools\x18\x02 \x03(\x08\x12\x0e\n\x06int32s\x18\x03 \x03(\x05\x12\x0e\n\x06int64s\x18\x04 \x03(\x03\x12\x10\n\x08\x66loat32s\x18\x05 \x03(\x02\x12\x10\n\x08\x66loat64s\x18\x06 \x03(\x01\x12#\n\x05lists\x18\x07 \x03(\x0b\x32\x14.nnextractor.NDArray\"\xe6\x01\n\x06Record\x12\x0c\n\x04type\x18\x01 \x01(\t\x12(\n\x05\x61rray\x18\x02 \x01(\x0b\x32\x14.nnextractor.NDArrayH\x00\x88\x01\x01\x12$\n\x07records\x18\x03 \x03(\x0b\x32\x13.nnextractor.Record\x12\x30\n\x07the_map\x18\x04 \x03(\x0b\x32\x1f.nnextractor.Record.TheMapEntry\x1a\x42\n\x0bTheMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.nnextractor.Record:\x02\x38\x01\x42\x08\n\x06_array\">\n\tParameter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12#\n\x06record\x18\x02 \x01(\x0b\x32\x13.nnextractor.Record\"\x8b\x01\n\nActivation\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\"\n\x05input\x18\x02 \x01(\x0b\x32\x13.nnextractor.Record\x12&\n\x06params\x18\x03 \x03(\x0b\x32\x16.nnextractor.Parameter\x12#\n\x06output\x18\x04 \x01(\x0b\x32\x13.nnextractor.Record\";\n\x0b\x41\x63tivations\x12,\n\x0b\x61\x63tivations\x18\x01 \x03(\x0b\x32\x17.nnextractor.Activationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nnextractor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECORD_THEMAPENTRY']._loaded_options = None
  _globals['_RECORD_THEMAPENTRY']._serialized_options = b'8\001'
  _globals['_NDARRAY']._serialized_start=35
  _globals['_NDARRAY']._serialized_end=178
  _globals['_RECORD']._serialized_start=181
  _globals['_RECORD']._serialized_end=411
  _globals['_RECORD_THEMAPENTRY']._serialized_start=335
  _globals['_RECORD_THEMAPENTRY']._serialized_end=401
  _globals['_PARAMETER']._serialized_start=413
  _globals['_PARAMETER']._serialized_end=475
  _globals['_ACTIVATION']._serialized_start=478
  _globals['_ACTIVATION']._serialized_end=617
  _globals['_ACTIVATIONS']._serialized_start=619
  _globals['_ACTIVATIONS']._serialized_end=678
# @@protoc_insertion_point(module_scope)
